### ISSUE TITLE
getVMs() of regionInstanceGroup

### ISSUE THREAD

**Issue by juliusza** [googleapis/nodejs-compute#146] opened 2018-09-04 14:32 UTC
#### Environment details

  - OS: Ubuntu 14.04.5 LTS
  - Node.js version: v8.11.3
  - npm version: 5.5.1
  - `@google-cloud/compute` version: 0.10.0

#### Steps to reproduce

```
'use strict';
const Compute = require('@google-cloud/compute');
const compute = new Compute();

async function main() {
   const [res] = await compute.getInstanceGroups({filter: "name = region-instance-group"});
   const instanceGroup = res[0];
   const vms = await instanceGroup.getVMs();
   console.log(vms);
}

main();
```

Expected:
* a list of virtual machines

Actual:
```
(node:16874) UnhandledPromiseRejectionWarning: ApiError: Error during request.
    at Object.parseHttpRespBody (/home/coordinator/test_compute/node_modules/@google-cloud/common/src/util.js:193:32)
    at Object.handleResp (/home/coordinator/test_compute/node_modules/@google-cloud/common/src/util.js:137:18)
    at /home/coordinator/test_compute/node_modules/@google-cloud/common/src/util.js:502:12
    at Request.onResponse [as _callback] (/home/coordinator/test_compute/node_modules/retry-request/index.js:198:7)
    at Request.self.callback (/home/coordinator/test_compute/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/coordinator/test_compute/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
```

This happens with region instance groups only (e.g. regions/europe-west1). I suspect this lib needs to implement regionInstanceGroups class: https://cloud.google.com/compute/docs/reference/rest/v1/regionInstanceGroups

**Comment by stephenplusplus** [comment] 2018-09-12 14:02
Managed instance groups will be supported through this PR: #104. There are still a few things left to do-- feel free to contribute, if you can! https://github.com/googleapis/nodejs-compute/pull/104#issuecomment-420629331

**Comment by stephenplusplus** [comment] 2018-09-12 14:03
*Closing as duplicate of #103.*

**Closed by stephenplusplus** 2018-09-12 14:03 UTC
Labels: type: feature request
