### ISSUE TITLE
vm.waitFor fails with 404 if zone is exhausted

### ISSUE THREAD

**Issue by zbjornson** [googleapis/nodejs-compute#377] opened 2019-12-17 20:49 UTC
#### Environment details

  - OS: Debian 8
  - Node.js version: 8.16.2
  - npm version: 6.4.1
  - `@google-cloud/compute` version: 1.1.8

#### Steps to reproduce

  1. Create a VM using `gce.zone("zone").createVM(name)` in a zone that doesn't have enough resources to launch the VM. This step succeeds and returns an operation with `status: "RUNNING"`. (*edited* I thought this was the VM status, but it's just the operation status.)

  2. Call `vm.waitFor("RUNNING")` on that instance. This step fails with

         Error: The resource 'projects/[proj]/zones/us-central1-f/instances/ci-62bbd20b071ae' was not found
            at Util.parseHttpRespBody (/home/zbjornson/ops/ci/node_modules/@google-cloud/common/build/src/util.js:191:38)
            ...
         code: 404

It would be useful if ~~either the first step didn't return "RUNNING" (which I know is a GCE API issue, not a nodejs-compute issue -- hopefully you can forward this as feedback) or if~~ `vm.waitFor` had a more helpful error message than a 404. It looks like the only way to improve the error message would be to [get the operation](https://cloud.google.com/compute/docs/reference/rest/v1/zoneOperations/get) so the error code can be inspected (it'll say `ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS`). Not sure if that's worth fixing given that it takes another API call, but then again you're already polling the "get instance" endpoint every 2s for `vm.waitFor`.

(Even if no change is made, hopefully this issue will help someone trying to figure out why they're getting 404s.)

**Comment by bcoe** [comment] 2020-06-15 22:57
@zbjornson at some point between this ticket being open and now, it looks like this error has been improved upstream. Here's what I did:

1. I created enough instances that I hit my quota in `europe-north1-a`.
2. I attempted to create an instance having hit the quota.
3. I got this error ` Error: Quota 'CPUS' exceeded.  Limit: 24.0 in region europe-north1`.

Let me know if I've misunderstood the bug report, closing for now 👍

**Comment by zbjornson** [comment] 2020-06-16 00:59
@bcoe I meant that the entire GCE zone is exhausted, not just the project quota.

**Comment by bcoe** [comment] 2020-06-16 22:25
@zbjornson

**Comment by bcoe** [comment] 2020-06-16 22:26
@zbjornson can you recommend a way to reproduce this behavior? It sounds like an upstream API issue where we should be passing a useful error message down, just as in the case where quota has been hit.

**Comment by zbjornson** [comment] 2020-06-18 18:36
@bcoe I can usually repro it with c2-standard machines in us-central1-c:

```js
const Compute = require('@google-cloud/compute');
const compute = new Compute();
const zone = compute.zone('us-central1-c');

async function launch() {
    const vmName = `vm-${Math.random().toString().replace('.', '')}`;
    const [vm] = await zone.createVM(vmName, {os: 'ubuntu', machineType: "c2-standard-16"});
    await vm.waitFor("RUNNING");
    console.log('Virtual machine created!');
}

async function main() {
        for (let i = 0; i < 10; i++)
                launch()
}
main();
```

Just now:

```
$ node ./test.js
Virtual machine created!
Virtual machine created!
(node:557) UnhandledPromiseRejectionWarning: Error: The resource 'projects/zbtest1/zones/us-central1-c/instances/vm-05341302486415749' was not found
    at new ApiError (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at Util.handleResp (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:135:117)
    at retryRequest (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:434:22)
    at onResponse (/home/zbjornson/test/node_modules/retry-request/index.js:206:7)
    at /home/zbjornson/test/node_modules/teeny-request/build/src/index.js:233:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:557) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Virtual machine created!
Virtual machine created!
Virtual machine created!
Virtual machine created!
Virtual machine created!
(node:557) UnhandledPromiseRejectionWarning: Error: The resource 'projects/zbtest1/zones/us-central1-c/instances/vm-03525735016150304' was not found
    at new ApiError (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at Util.handleResp (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:135:117)
    at retryRequest (/home/zbjornson/test/node_modules/@google-cloud/common/build/src/util.js:434:22)
    at onResponse (/home/zbjornson/test/node_modules/retry-request/index.js:206:7)
    at /home/zbjornson/test/node_modules/teeny-request/build/src/index.js:233:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Virtual machine created!
```

> It sounds like an upstream API issue where we should be passing a useful error message down

Indeed, in the OP I mentioned that it seems wrong for the `create` call to return `RUNNING`. I didn't dissect the issue to know exactly where the failure/best remedy is though.

**Comment by zbjornson** [comment] 2020-08-31 18:36
I just edited the OP to clarify some points after digging into this more. In particular, the initial "RUNNING" status refers to the operation and not the VM. The 404 happens because GCE deletes the VM in case of certain errors like the one I posted, so the `GET metadata` request fails. Polling the operation status doesn't have this issue, but only lets you wait for the operation to complete, whereas `vm.waitFor` lets you wait for VM statuses.

**Comment by rostow** [comment] 2020-09-28 09:15
I was getting exactly the same error and couldn't figure out why. Thanks raising the issue!

As I understand, on ```PROVISIONING``` GCE tries to allocate the necessary resources for the VM being created. Shouldn't ```vm.waitFor('PROVISIONING')``` throw an error already if not enough resources are available (preventing it this way to continue to the ```STAGING``` event)?

Right now I have to listen for ```operation.on('error')```. Perhaps this is the expected behavior but I believe throwing the error on provisioning would be more intuitive.

**Comment by sofisl** [comment] 2022-06-23 18:24
Hi, please refer to the new library, ^3.0.0.

**Closed by sofisl** 2022-06-23 18:24 UTC
Labels: type: bug, priority: p2, external, api: compute
